###
GET http://localhost:3000

### יצירת פוסט חדש 
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "First Post",
    "content": "This is the content of the first post.",
    "sender": "user123"
}
### קבלת כל הפוסטים
GET http://localhost:3000/posts 

### קבלת פוסט לפי מזהה
GET http://localhost:3000/posts/67483a0151ed21e92836fa4f

### קבלת פוסטים לפי שולח
GET http://localhost:3000/posts?sender=user123

### עדכון פוסט
PUT http://localhost:3000/posts/67483a0151ed21e92836fa4f
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content."
}

###

DELETE http://localhost:3000/posts/67483a0151ed21e92836fa4f

###






