### New post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "First Post",
    "content": "This is the content of the first post.",
    "sender": "user123"
}
### GET all posts
GET http://localhost:3000/posts 

### GET post by id
GET http://localhost:3000/posts/67697ba9aa20ac4a78cfcabe

### GET post by sender
GET http://localhost:3000/posts?sender=user123

### Update post
PUT http://localhost:3000/posts/67697ba9aa20ac4a78cfcabe
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content."
}

###
DELETE http://localhost:3000/posts/67697ba9aa20ac4a78cfcabe


### -----------------------------------------------

### New comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "comment": "This is a comment",
    "postId": "6762bd9992528cab8f5c4394",
    "sender": "user123"
}

### GET all comments
GET http://localhost:3000/comments

### GET comment by id
GET http://localhost:3000/comments/67697bddaa20ac4a78cfcac3

### GET comments by postId
GET http://localhost:3000/comments/post/6762bd9992528cab8f5c4394

### Update comment
PUT http://localhost:3000/comments/67697bddaa20ac4a78cfcac3
Content-Type: application/json

{
    "comment": "This is the updated comment content"
 
}

###
DELETE http://localhost:3000/comments/67697bddaa20ac4a78cfcac3




