
### New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "First Post",
    "content": "This is the content of the first post.",
    "sender": "user1235"
}
### GET all posts
GET http://localhost:3000/posts 

### GET post by id
GET http://localhost:3000/posts/677a6a8bf43f72edf496012e

### GET post by sender
GET http://localhost:3000/posts?sender=user123

### Update post
PUT http://localhost:3000/posts/677a6a8bf43f72edf496012e
Content-Type: application/json

{
    "title": "Updated Title",
    "content": "Updated content."
}

###
DELETE http://localhost:3000/posts/6779bde73d2f7765421ec20d


### -----------------------------------------------

### New Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "comment": "This is a comment",
    "postId": "677bf4b38e6ec192af54bf9c",
    "sender": "user123"
  
}

### GET all comments
GET http://localhost:3000/comments

### GET comment by id
GET http://localhost:3000/comments/677a6c69ba3602a3f7812067

### GET comments by postId
GET http://localhost:3000/comments/post/677bf4b38e6ec192af54bf9c

### Update comment
PUT http://localhost:3000/comments/677a6c6aba3602a3f7812069
Content-Type: application/json

{
    "comment": "This is the updated comment content"
 
}

###
DELETE http://localhost:3000/comments/677a6b74ba3602a3f7812051




